### PR TITLE
Add initial Gradle build

### PR DESCRIPTION
**Pull request by denuno**
I've got one for the Utilities too, but that's going to need some input... @dorkbox do you have a script for making that like you did for this?  Seems like you split it out into sub-utilities (heh) somehow?  Gradle can do that easily too, just need to know what goes where.  Here's an initial go tho.  Refs #81 

FWIW, I'm really liking using a git-tag based versioning setup, with that it's a -SNAPSHOT until tagged so you don't have to keep modifying the sources just to set a version (and it has the number of commits different and whatnot thus kinda useful to measure change).

### CODE REVIEW

**Comment by dorkbox** [comment]
wow, this should do nicely. Thanks! 

So each project I have makes it's own build of utilities - and there isn't a "main" utilities build outside of existing as an intellij module... 

I'm neck deep in some netcode right now, and I'll merge/add this as soon as I'm able.

**Comment by dorkbox** [comment]
So I'm onto the gradle stuff now -- @denuno, what do you mean be a script? Those were done by hand... :P 

The Utilities live as an IntelliJ module and when I build the different github projects, I include whatever files are necessary to compile. Almost all of the projects I have on github started off in "Utilities", and I've slowly been moving them into their own project as they grow.

Also, how do you do the git-tagging stuff?

**Comment by denuno** [comment]
For the git tags you do something like `git tag -a x.y.z` and then enter a description, and after that `git describe` will show what it sees as the difference between versions.  I'm still on the fence about using it to auto-version number, but it's always good to tag release versions in git regardless.

As for the Utilities, I'm looking at Java 9+ and we'll need to split things out a little more I think (I'm getting messages about mixed packages from dorkbox.util).

**Comment by dorkbox** [comment]
Just got a gradle build working with all sorts of magic crap to get the test example jars to build and to have utilities be a subproject, but not all of it -- just the applicable portion. 

A huge PITA to get all that working, but that goes when learning anything new that is complex... and wow the official gradle examples are anything but useful. They should rewrite the esoteric meta-build crap into the context of compiling a java project. </rant>

Anyways, thanks for the original build file -- it was tremendously helpful.

**Comment by denuno** [comment]
Sure thing!  I have found it's more useful to search other gradle files for examples of stuff than it is to search the official docs.  I'm quite impressed with the kotlin version you've come up with, massive props for getting that together!

FWIW the java 9+ compat stuff will initially just be splitting the bits that are currently included from dorkbox.util in both SystemTray and Notify into their own jar instead, and then eventually making stuff into modules (a lot has changed between java 8 and 9 though for projects like this).

For now I'm making an uber jar of the SystemTray+Notify projects, and that seems to work okay, though I am getting intermittent errors that kill the whole process... but I was getting that before the merge so.... I'll file a ticket when I track down which project it's coming from-- the error is this tho in case it rings a bell:
>The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 2333 error_code 143 request_code 139 minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Anyhow, I'm going to close this now, and again, :heart: the new build!

**Pull request closed without merging**
